# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  openWeatherConnectorDemo:
    # Default city for searching weather
    defaultSearchedCity: 'New York'
    
    # Default units for searching weather
    defaultUnits: 'metric'
