/*
 * Openweathermap geocoding API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.geo1_0.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * LocalNames
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:09:12.249209900+07:00[Asia/Bangkok]")
public class LocalNames {
  @JsonProperty("ab")
  private String ab = null;

  @JsonProperty("af")
  private String af = null;

  @JsonProperty("an")
  private String an = null;

  @JsonProperty("ar")
  private String ar = null;

  @JsonProperty("av")
  private String av = null;

  @JsonProperty("ay")
  private String ay = null;

  @JsonProperty("az")
  private String az = null;

  @JsonProperty("be")
  private String be = null;

  @JsonProperty("bg")
  private String bg = null;

  @JsonProperty("bh")
  private String bh = null;

  @JsonProperty("bi")
  private String bi = null;

  @JsonProperty("bm")
  private String bm = null;

  @JsonProperty("bn")
  private String bn = null;

  @JsonProperty("bo")
  private String bo = null;

  @JsonProperty("br")
  private String br = null;

  @JsonProperty("bs")
  private String bs = null;

  @JsonProperty("ca")
  private String ca = null;

  @JsonProperty("ce")
  private String ce = null;

  @JsonProperty("co")
  private String co = null;

  @JsonProperty("cs")
  private String cs = null;

  @JsonProperty("cu")
  private String cu = null;

  @JsonProperty("cy")
  private String cy = null;

  @JsonProperty("da")
  private String da = null;

  @JsonProperty("de")
  private String de = null;

  @JsonProperty("ee")
  private String ee = null;

  @JsonProperty("el")
  private String el = null;

  @JsonProperty("en")
  private String en = null;

  @JsonProperty("eo")
  private String eo = null;

  @JsonProperty("es")
  private String es = null;

  @JsonProperty("et")
  private String et = null;

  @JsonProperty("eu")
  private String eu = null;

  @JsonProperty("fa")
  private String fa = null;

  @JsonProperty("ff")
  private String ff = null;

  @JsonProperty("fi")
  private String fi = null;

  @JsonProperty("fj")
  private String fj = null;

  @JsonProperty("fo")
  private String fo = null;

  @JsonProperty("fr")
  private String fr = null;

  @JsonProperty("fy")
  private String fy = null;

  @JsonProperty("ga")
  private String ga = null;

  @JsonProperty("gd")
  private String gd = null;

  @JsonProperty("gl")
  private String gl = null;

  @JsonProperty("gn")
  private String gn = null;

  @JsonProperty("gu")
  private String gu = null;

  @JsonProperty("ha")
  private String ha = null;

  @JsonProperty("he")
  private String he = null;

  @JsonProperty("hi")
  private String hi = null;

  @JsonProperty("hr")
  private String hr = null;

  @JsonProperty("ht")
  private String ht = null;

  @JsonProperty("hu")
  private String hu = null;

  @JsonProperty("ia")
  private String ia = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("ig")
  private String ig = null;

  @JsonProperty("is")
  private String is = null;

  @JsonProperty("it")
  private String it = null;

  @JsonProperty("ja")
  private String ja = null;

  @JsonProperty("jv")
  private String jv = null;

  @JsonProperty("ka")
  private String ka = null;

  @JsonProperty("kk")
  private String kk = null;

  @JsonProperty("km")
  private String km = null;

  @JsonProperty("kn")
  private String kn = null;

  @JsonProperty("ko")
  private String ko = null;

  @JsonProperty("ku")
  private String ku = null;

  @JsonProperty("kw")
  private String kw = null;

  @JsonProperty("ky")
  private String ky = null;

  @JsonProperty("lb")
  private String lb = null;

  @JsonProperty("li")
  private String li = null;

  @JsonProperty("ln")
  private String ln = null;

  @JsonProperty("lo")
  private String lo = null;

  @JsonProperty("lt")
  private String lt = null;

  @JsonProperty("lv")
  private String lv = null;

  @JsonProperty("mg")
  private String mg = null;

  @JsonProperty("mi")
  private String mi = null;

  @JsonProperty("mk")
  private String mk = null;

  @JsonProperty("ml")
  private String ml = null;

  @JsonProperty("mn")
  private String mn = null;

  @JsonProperty("mr")
  private String mr = null;

  @JsonProperty("ms")
  private String ms = null;

  @JsonProperty("mt")
  private String mt = null;

  @JsonProperty("my")
  private String my = null;

  @JsonProperty("na")
  private String na = null;

  @JsonProperty("nb")
  private String nb = null;

  @JsonProperty("ne")
  private String ne = null;

  @JsonProperty("nl")
  private String nl = null;

  @JsonProperty("nn")
  private String nn = null;

  @JsonProperty("no")
  private String no = null;

  @JsonProperty("nv")
  private String nv = null;

  @JsonProperty("ny")
  private String ny = null;

  @JsonProperty("oc")
  private String oc = null;

  @JsonProperty("or")
  private String or = null;

  @JsonProperty("os")
  private String os = null;

  @JsonProperty("pa")
  private String pa = null;

  @JsonProperty("pl")
  private String pl = null;

  @JsonProperty("ps")
  private String ps = null;

  @JsonProperty("pt")
  private String pt = null;

  @JsonProperty("qu")
  private String qu = null;

  @JsonProperty("ro")
  private String ro = null;

  @JsonProperty("ru")
  private String ru = null;

  @JsonProperty("rw")
  private String rw = null;

  @JsonProperty("sc")
  private String sc = null;

  @JsonProperty("sd")
  private String sd = null;

  @JsonProperty("se")
  private String se = null;

  @JsonProperty("si")
  private String si = null;

  @JsonProperty("sk")
  private String sk = null;

  @JsonProperty("sl")
  private String sl = null;

  @JsonProperty("sm")
  private String sm = null;

  @JsonProperty("so")
  private String so = null;

  @JsonProperty("sq")
  private String sq = null;

  @JsonProperty("sr")
  private String sr = null;

  @JsonProperty("st")
  private String st = null;

  @JsonProperty("sv")
  private String sv = null;

  @JsonProperty("sw")
  private String sw = null;

  @JsonProperty("ta")
  private String ta = null;

  @JsonProperty("te")
  private String te = null;

  @JsonProperty("tg")
  private String tg = null;

  @JsonProperty("th")
  private String th = null;

  @JsonProperty("tl")
  private String tl = null;

  @JsonProperty("to")
  private String to = null;

  @JsonProperty("tr")
  private String tr = null;

  @JsonProperty("tw")
  private String tw = null;

  @JsonProperty("ug")
  private String ug = null;

  @JsonProperty("uk")
  private String uk = null;

  @JsonProperty("ur")
  private String ur = null;

  @JsonProperty("uz")
  private String uz = null;

  @JsonProperty("vi")
  private String vi = null;

  @JsonProperty("wo")
  private String wo = null;

  @JsonProperty("xh")
  private String xh = null;

  @JsonProperty("yi")
  private String yi = null;

  @JsonProperty("yo")
  private String yo = null;

  @JsonProperty("zh")
  private String zh = null;

  @JsonProperty("zu")
  private String zu = null;

  @JsonProperty("ascii")
  private String ascii = null;

  @JsonProperty("feature_name")
  private String featureName = null;

  public LocalNames ab(String ab) {
    this.ab = ab;
    return this;
  }

   /**
   * Get ab
   * @return ab
  **/
  public String getAb() {
    return ab;
  }

  public void setAb(String ab) {
    this.ab = ab;
  }

  public LocalNames af(String af) {
    this.af = af;
    return this;
  }

   /**
   * Get af
   * @return af
  **/
  public String getAf() {
    return af;
  }

  public void setAf(String af) {
    this.af = af;
  }

  public LocalNames an(String an) {
    this.an = an;
    return this;
  }

   /**
   * Get an
   * @return an
  **/
  public String getAn() {
    return an;
  }

  public void setAn(String an) {
    this.an = an;
  }

  public LocalNames ar(String ar) {
    this.ar = ar;
    return this;
  }

   /**
   * Get ar
   * @return ar
  **/
  public String getAr() {
    return ar;
  }

  public void setAr(String ar) {
    this.ar = ar;
  }

  public LocalNames av(String av) {
    this.av = av;
    return this;
  }

   /**
   * Get av
   * @return av
  **/
  public String getAv() {
    return av;
  }

  public void setAv(String av) {
    this.av = av;
  }

  public LocalNames ay(String ay) {
    this.ay = ay;
    return this;
  }

   /**
   * Get ay
   * @return ay
  **/
  public String getAy() {
    return ay;
  }

  public void setAy(String ay) {
    this.ay = ay;
  }

  public LocalNames az(String az) {
    this.az = az;
    return this;
  }

   /**
   * Get az
   * @return az
  **/
  public String getAz() {
    return az;
  }

  public void setAz(String az) {
    this.az = az;
  }

  public LocalNames be(String be) {
    this.be = be;
    return this;
  }

   /**
   * Get be
   * @return be
  **/
  public String getBe() {
    return be;
  }

  public void setBe(String be) {
    this.be = be;
  }

  public LocalNames bg(String bg) {
    this.bg = bg;
    return this;
  }

   /**
   * Get bg
   * @return bg
  **/
  public String getBg() {
    return bg;
  }

  public void setBg(String bg) {
    this.bg = bg;
  }

  public LocalNames bh(String bh) {
    this.bh = bh;
    return this;
  }

   /**
   * Get bh
   * @return bh
  **/
  public String getBh() {
    return bh;
  }

  public void setBh(String bh) {
    this.bh = bh;
  }

  public LocalNames bi(String bi) {
    this.bi = bi;
    return this;
  }

   /**
   * Get bi
   * @return bi
  **/
  public String getBi() {
    return bi;
  }

  public void setBi(String bi) {
    this.bi = bi;
  }

  public LocalNames bm(String bm) {
    this.bm = bm;
    return this;
  }

   /**
   * Get bm
   * @return bm
  **/
  public String getBm() {
    return bm;
  }

  public void setBm(String bm) {
    this.bm = bm;
  }

  public LocalNames bn(String bn) {
    this.bn = bn;
    return this;
  }

   /**
   * Get bn
   * @return bn
  **/
  public String getBn() {
    return bn;
  }

  public void setBn(String bn) {
    this.bn = bn;
  }

  public LocalNames bo(String bo) {
    this.bo = bo;
    return this;
  }

   /**
   * Get bo
   * @return bo
  **/
  public String getBo() {
    return bo;
  }

  public void setBo(String bo) {
    this.bo = bo;
  }

  public LocalNames br(String br) {
    this.br = br;
    return this;
  }

   /**
   * Get br
   * @return br
  **/
  public String getBr() {
    return br;
  }

  public void setBr(String br) {
    this.br = br;
  }

  public LocalNames bs(String bs) {
    this.bs = bs;
    return this;
  }

   /**
   * Get bs
   * @return bs
  **/
  public String getBs() {
    return bs;
  }

  public void setBs(String bs) {
    this.bs = bs;
  }

  public LocalNames ca(String ca) {
    this.ca = ca;
    return this;
  }

   /**
   * Get ca
   * @return ca
  **/
  public String getCa() {
    return ca;
  }

  public void setCa(String ca) {
    this.ca = ca;
  }

  public LocalNames ce(String ce) {
    this.ce = ce;
    return this;
  }

   /**
   * Get ce
   * @return ce
  **/
  public String getCe() {
    return ce;
  }

  public void setCe(String ce) {
    this.ce = ce;
  }

  public LocalNames co(String co) {
    this.co = co;
    return this;
  }

   /**
   * Get co
   * @return co
  **/
  public String getCo() {
    return co;
  }

  public void setCo(String co) {
    this.co = co;
  }

  public LocalNames cs(String cs) {
    this.cs = cs;
    return this;
  }

   /**
   * Get cs
   * @return cs
  **/
  public String getCs() {
    return cs;
  }

  public void setCs(String cs) {
    this.cs = cs;
  }

  public LocalNames cu(String cu) {
    this.cu = cu;
    return this;
  }

   /**
   * Get cu
   * @return cu
  **/
  public String getCu() {
    return cu;
  }

  public void setCu(String cu) {
    this.cu = cu;
  }

  public LocalNames cy(String cy) {
    this.cy = cy;
    return this;
  }

   /**
   * Get cy
   * @return cy
  **/
  public String getCy() {
    return cy;
  }

  public void setCy(String cy) {
    this.cy = cy;
  }

  public LocalNames da(String da) {
    this.da = da;
    return this;
  }

   /**
   * Get da
   * @return da
  **/
  public String getDa() {
    return da;
  }

  public void setDa(String da) {
    this.da = da;
  }

  public LocalNames de(String de) {
    this.de = de;
    return this;
  }

   /**
   * Get de
   * @return de
  **/
  public String getDe() {
    return de;
  }

  public void setDe(String de) {
    this.de = de;
  }

  public LocalNames ee(String ee) {
    this.ee = ee;
    return this;
  }

   /**
   * Get ee
   * @return ee
  **/
  public String getEe() {
    return ee;
  }

  public void setEe(String ee) {
    this.ee = ee;
  }

  public LocalNames el(String el) {
    this.el = el;
    return this;
  }

   /**
   * Get el
   * @return el
  **/
  public String getEl() {
    return el;
  }

  public void setEl(String el) {
    this.el = el;
  }

  public LocalNames en(String en) {
    this.en = en;
    return this;
  }

   /**
   * Get en
   * @return en
  **/
  public String getEn() {
    return en;
  }

  public void setEn(String en) {
    this.en = en;
  }

  public LocalNames eo(String eo) {
    this.eo = eo;
    return this;
  }

   /**
   * Get eo
   * @return eo
  **/
  public String getEo() {
    return eo;
  }

  public void setEo(String eo) {
    this.eo = eo;
  }

  public LocalNames es(String es) {
    this.es = es;
    return this;
  }

   /**
   * Get es
   * @return es
  **/
  public String getEs() {
    return es;
  }

  public void setEs(String es) {
    this.es = es;
  }

  public LocalNames et(String et) {
    this.et = et;
    return this;
  }

   /**
   * Get et
   * @return et
  **/
  public String getEt() {
    return et;
  }

  public void setEt(String et) {
    this.et = et;
  }

  public LocalNames eu(String eu) {
    this.eu = eu;
    return this;
  }

   /**
   * Get eu
   * @return eu
  **/
  public String getEu() {
    return eu;
  }

  public void setEu(String eu) {
    this.eu = eu;
  }

  public LocalNames fa(String fa) {
    this.fa = fa;
    return this;
  }

   /**
   * Get fa
   * @return fa
  **/
  public String getFa() {
    return fa;
  }

  public void setFa(String fa) {
    this.fa = fa;
  }

  public LocalNames ff(String ff) {
    this.ff = ff;
    return this;
  }

   /**
   * Get ff
   * @return ff
  **/
  public String getFf() {
    return ff;
  }

  public void setFf(String ff) {
    this.ff = ff;
  }

  public LocalNames fi(String fi) {
    this.fi = fi;
    return this;
  }

   /**
   * Get fi
   * @return fi
  **/
  public String getFi() {
    return fi;
  }

  public void setFi(String fi) {
    this.fi = fi;
  }

  public LocalNames fj(String fj) {
    this.fj = fj;
    return this;
  }

   /**
   * Get fj
   * @return fj
  **/
  public String getFj() {
    return fj;
  }

  public void setFj(String fj) {
    this.fj = fj;
  }

  public LocalNames fo(String fo) {
    this.fo = fo;
    return this;
  }

   /**
   * Get fo
   * @return fo
  **/
  public String getFo() {
    return fo;
  }

  public void setFo(String fo) {
    this.fo = fo;
  }

  public LocalNames fr(String fr) {
    this.fr = fr;
    return this;
  }

   /**
   * Get fr
   * @return fr
  **/
  public String getFr() {
    return fr;
  }

  public void setFr(String fr) {
    this.fr = fr;
  }

  public LocalNames fy(String fy) {
    this.fy = fy;
    return this;
  }

   /**
   * Get fy
   * @return fy
  **/
  public String getFy() {
    return fy;
  }

  public void setFy(String fy) {
    this.fy = fy;
  }

  public LocalNames ga(String ga) {
    this.ga = ga;
    return this;
  }

   /**
   * Get ga
   * @return ga
  **/
  public String getGa() {
    return ga;
  }

  public void setGa(String ga) {
    this.ga = ga;
  }

  public LocalNames gd(String gd) {
    this.gd = gd;
    return this;
  }

   /**
   * Get gd
   * @return gd
  **/
  public String getGd() {
    return gd;
  }

  public void setGd(String gd) {
    this.gd = gd;
  }

  public LocalNames gl(String gl) {
    this.gl = gl;
    return this;
  }

   /**
   * Get gl
   * @return gl
  **/
  public String getGl() {
    return gl;
  }

  public void setGl(String gl) {
    this.gl = gl;
  }

  public LocalNames gn(String gn) {
    this.gn = gn;
    return this;
  }

   /**
   * Get gn
   * @return gn
  **/
  public String getGn() {
    return gn;
  }

  public void setGn(String gn) {
    this.gn = gn;
  }

  public LocalNames gu(String gu) {
    this.gu = gu;
    return this;
  }

   /**
   * Get gu
   * @return gu
  **/
  public String getGu() {
    return gu;
  }

  public void setGu(String gu) {
    this.gu = gu;
  }

  public LocalNames ha(String ha) {
    this.ha = ha;
    return this;
  }

   /**
   * Get ha
   * @return ha
  **/
  public String getHa() {
    return ha;
  }

  public void setHa(String ha) {
    this.ha = ha;
  }

  public LocalNames he(String he) {
    this.he = he;
    return this;
  }

   /**
   * Get he
   * @return he
  **/
  public String getHe() {
    return he;
  }

  public void setHe(String he) {
    this.he = he;
  }

  public LocalNames hi(String hi) {
    this.hi = hi;
    return this;
  }

   /**
   * Get hi
   * @return hi
  **/
  public String getHi() {
    return hi;
  }

  public void setHi(String hi) {
    this.hi = hi;
  }

  public LocalNames hr(String hr) {
    this.hr = hr;
    return this;
  }

   /**
   * Get hr
   * @return hr
  **/
  public String getHr() {
    return hr;
  }

  public void setHr(String hr) {
    this.hr = hr;
  }

  public LocalNames ht(String ht) {
    this.ht = ht;
    return this;
  }

   /**
   * Get ht
   * @return ht
  **/
  public String getHt() {
    return ht;
  }

  public void setHt(String ht) {
    this.ht = ht;
  }

  public LocalNames hu(String hu) {
    this.hu = hu;
    return this;
  }

   /**
   * Get hu
   * @return hu
  **/
  public String getHu() {
    return hu;
  }

  public void setHu(String hu) {
    this.hu = hu;
  }

  public LocalNames ia(String ia) {
    this.ia = ia;
    return this;
  }

   /**
   * Get ia
   * @return ia
  **/
  public String getIa() {
    return ia;
  }

  public void setIa(String ia) {
    this.ia = ia;
  }

  public LocalNames id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public LocalNames ig(String ig) {
    this.ig = ig;
    return this;
  }

   /**
   * Get ig
   * @return ig
  **/
  public String getIg() {
    return ig;
  }

  public void setIg(String ig) {
    this.ig = ig;
  }

  public LocalNames is(String is) {
    this.is = is;
    return this;
  }

   /**
   * Get is
   * @return is
  **/
  public String getIs() {
    return is;
  }

  public void setIs(String is) {
    this.is = is;
  }

  public LocalNames it(String it) {
    this.it = it;
    return this;
  }

   /**
   * Get it
   * @return it
  **/
  public String getIt() {
    return it;
  }

  public void setIt(String it) {
    this.it = it;
  }

  public LocalNames ja(String ja) {
    this.ja = ja;
    return this;
  }

   /**
   * Get ja
   * @return ja
  **/
  public String getJa() {
    return ja;
  }

  public void setJa(String ja) {
    this.ja = ja;
  }

  public LocalNames jv(String jv) {
    this.jv = jv;
    return this;
  }

   /**
   * Get jv
   * @return jv
  **/
  public String getJv() {
    return jv;
  }

  public void setJv(String jv) {
    this.jv = jv;
  }

  public LocalNames ka(String ka) {
    this.ka = ka;
    return this;
  }

   /**
   * Get ka
   * @return ka
  **/
  public String getKa() {
    return ka;
  }

  public void setKa(String ka) {
    this.ka = ka;
  }

  public LocalNames kk(String kk) {
    this.kk = kk;
    return this;
  }

   /**
   * Get kk
   * @return kk
  **/
  public String getKk() {
    return kk;
  }

  public void setKk(String kk) {
    this.kk = kk;
  }

  public LocalNames km(String km) {
    this.km = km;
    return this;
  }

   /**
   * Get km
   * @return km
  **/
  public String getKm() {
    return km;
  }

  public void setKm(String km) {
    this.km = km;
  }

  public LocalNames kn(String kn) {
    this.kn = kn;
    return this;
  }

   /**
   * Get kn
   * @return kn
  **/
  public String getKn() {
    return kn;
  }

  public void setKn(String kn) {
    this.kn = kn;
  }

  public LocalNames ko(String ko) {
    this.ko = ko;
    return this;
  }

   /**
   * Get ko
   * @return ko
  **/
  public String getKo() {
    return ko;
  }

  public void setKo(String ko) {
    this.ko = ko;
  }

  public LocalNames ku(String ku) {
    this.ku = ku;
    return this;
  }

   /**
   * Get ku
   * @return ku
  **/
  public String getKu() {
    return ku;
  }

  public void setKu(String ku) {
    this.ku = ku;
  }

  public LocalNames kw(String kw) {
    this.kw = kw;
    return this;
  }

   /**
   * Get kw
   * @return kw
  **/
  public String getKw() {
    return kw;
  }

  public void setKw(String kw) {
    this.kw = kw;
  }

  public LocalNames ky(String ky) {
    this.ky = ky;
    return this;
  }

   /**
   * Get ky
   * @return ky
  **/
  public String getKy() {
    return ky;
  }

  public void setKy(String ky) {
    this.ky = ky;
  }

  public LocalNames lb(String lb) {
    this.lb = lb;
    return this;
  }

   /**
   * Get lb
   * @return lb
  **/
  public String getLb() {
    return lb;
  }

  public void setLb(String lb) {
    this.lb = lb;
  }

  public LocalNames li(String li) {
    this.li = li;
    return this;
  }

   /**
   * Get li
   * @return li
  **/
  public String getLi() {
    return li;
  }

  public void setLi(String li) {
    this.li = li;
  }

  public LocalNames ln(String ln) {
    this.ln = ln;
    return this;
  }

   /**
   * Get ln
   * @return ln
  **/
  public String getLn() {
    return ln;
  }

  public void setLn(String ln) {
    this.ln = ln;
  }

  public LocalNames lo(String lo) {
    this.lo = lo;
    return this;
  }

   /**
   * Get lo
   * @return lo
  **/
  public String getLo() {
    return lo;
  }

  public void setLo(String lo) {
    this.lo = lo;
  }

  public LocalNames lt(String lt) {
    this.lt = lt;
    return this;
  }

   /**
   * Get lt
   * @return lt
  **/
  public String getLt() {
    return lt;
  }

  public void setLt(String lt) {
    this.lt = lt;
  }

  public LocalNames lv(String lv) {
    this.lv = lv;
    return this;
  }

   /**
   * Get lv
   * @return lv
  **/
  public String getLv() {
    return lv;
  }

  public void setLv(String lv) {
    this.lv = lv;
  }

  public LocalNames mg(String mg) {
    this.mg = mg;
    return this;
  }

   /**
   * Get mg
   * @return mg
  **/
  public String getMg() {
    return mg;
  }

  public void setMg(String mg) {
    this.mg = mg;
  }

  public LocalNames mi(String mi) {
    this.mi = mi;
    return this;
  }

   /**
   * Get mi
   * @return mi
  **/
  public String getMi() {
    return mi;
  }

  public void setMi(String mi) {
    this.mi = mi;
  }

  public LocalNames mk(String mk) {
    this.mk = mk;
    return this;
  }

   /**
   * Get mk
   * @return mk
  **/
  public String getMk() {
    return mk;
  }

  public void setMk(String mk) {
    this.mk = mk;
  }

  public LocalNames ml(String ml) {
    this.ml = ml;
    return this;
  }

   /**
   * Get ml
   * @return ml
  **/
  public String getMl() {
    return ml;
  }

  public void setMl(String ml) {
    this.ml = ml;
  }

  public LocalNames mn(String mn) {
    this.mn = mn;
    return this;
  }

   /**
   * Get mn
   * @return mn
  **/
  public String getMn() {
    return mn;
  }

  public void setMn(String mn) {
    this.mn = mn;
  }

  public LocalNames mr(String mr) {
    this.mr = mr;
    return this;
  }

   /**
   * Get mr
   * @return mr
  **/
  public String getMr() {
    return mr;
  }

  public void setMr(String mr) {
    this.mr = mr;
  }

  public LocalNames ms(String ms) {
    this.ms = ms;
    return this;
  }

   /**
   * Get ms
   * @return ms
  **/
  public String getMs() {
    return ms;
  }

  public void setMs(String ms) {
    this.ms = ms;
  }

  public LocalNames mt(String mt) {
    this.mt = mt;
    return this;
  }

   /**
   * Get mt
   * @return mt
  **/
  public String getMt() {
    return mt;
  }

  public void setMt(String mt) {
    this.mt = mt;
  }

  public LocalNames my(String my) {
    this.my = my;
    return this;
  }

   /**
   * Get my
   * @return my
  **/
  public String getMy() {
    return my;
  }

  public void setMy(String my) {
    this.my = my;
  }

  public LocalNames na(String na) {
    this.na = na;
    return this;
  }

   /**
   * Get na
   * @return na
  **/
  public String getNa() {
    return na;
  }

  public void setNa(String na) {
    this.na = na;
  }

  public LocalNames nb(String nb) {
    this.nb = nb;
    return this;
  }

   /**
   * Get nb
   * @return nb
  **/
  public String getNb() {
    return nb;
  }

  public void setNb(String nb) {
    this.nb = nb;
  }

  public LocalNames ne(String ne) {
    this.ne = ne;
    return this;
  }

   /**
   * Get ne
   * @return ne
  **/
  public String getNe() {
    return ne;
  }

  public void setNe(String ne) {
    this.ne = ne;
  }

  public LocalNames nl(String nl) {
    this.nl = nl;
    return this;
  }

   /**
   * Get nl
   * @return nl
  **/
  public String getNl() {
    return nl;
  }

  public void setNl(String nl) {
    this.nl = nl;
  }

  public LocalNames nn(String nn) {
    this.nn = nn;
    return this;
  }

   /**
   * Get nn
   * @return nn
  **/
  public String getNn() {
    return nn;
  }

  public void setNn(String nn) {
    this.nn = nn;
  }

  public LocalNames no(String no) {
    this.no = no;
    return this;
  }

   /**
   * Get no
   * @return no
  **/
  public String getNo() {
    return no;
  }

  public void setNo(String no) {
    this.no = no;
  }

  public LocalNames nv(String nv) {
    this.nv = nv;
    return this;
  }

   /**
   * Get nv
   * @return nv
  **/
  public String getNv() {
    return nv;
  }

  public void setNv(String nv) {
    this.nv = nv;
  }

  public LocalNames ny(String ny) {
    this.ny = ny;
    return this;
  }

   /**
   * Get ny
   * @return ny
  **/
  public String getNy() {
    return ny;
  }

  public void setNy(String ny) {
    this.ny = ny;
  }

  public LocalNames oc(String oc) {
    this.oc = oc;
    return this;
  }

   /**
   * Get oc
   * @return oc
  **/
  public String getOc() {
    return oc;
  }

  public void setOc(String oc) {
    this.oc = oc;
  }

  public LocalNames or(String or) {
    this.or = or;
    return this;
  }

   /**
   * Get or
   * @return or
  **/
  public String getOr() {
    return or;
  }

  public void setOr(String or) {
    this.or = or;
  }

  public LocalNames os(String os) {
    this.os = os;
    return this;
  }

   /**
   * Get os
   * @return os
  **/
  public String getOs() {
    return os;
  }

  public void setOs(String os) {
    this.os = os;
  }

  public LocalNames pa(String pa) {
    this.pa = pa;
    return this;
  }

   /**
   * Get pa
   * @return pa
  **/
  public String getPa() {
    return pa;
  }

  public void setPa(String pa) {
    this.pa = pa;
  }

  public LocalNames pl(String pl) {
    this.pl = pl;
    return this;
  }

   /**
   * Get pl
   * @return pl
  **/
  public String getPl() {
    return pl;
  }

  public void setPl(String pl) {
    this.pl = pl;
  }

  public LocalNames ps(String ps) {
    this.ps = ps;
    return this;
  }

   /**
   * Get ps
   * @return ps
  **/
  public String getPs() {
    return ps;
  }

  public void setPs(String ps) {
    this.ps = ps;
  }

  public LocalNames pt(String pt) {
    this.pt = pt;
    return this;
  }

   /**
   * Get pt
   * @return pt
  **/
  public String getPt() {
    return pt;
  }

  public void setPt(String pt) {
    this.pt = pt;
  }

  public LocalNames qu(String qu) {
    this.qu = qu;
    return this;
  }

   /**
   * Get qu
   * @return qu
  **/
  public String getQu() {
    return qu;
  }

  public void setQu(String qu) {
    this.qu = qu;
  }

  public LocalNames ro(String ro) {
    this.ro = ro;
    return this;
  }

   /**
   * Get ro
   * @return ro
  **/
  public String getRo() {
    return ro;
  }

  public void setRo(String ro) {
    this.ro = ro;
  }

  public LocalNames ru(String ru) {
    this.ru = ru;
    return this;
  }

   /**
   * Get ru
   * @return ru
  **/
  public String getRu() {
    return ru;
  }

  public void setRu(String ru) {
    this.ru = ru;
  }

  public LocalNames rw(String rw) {
    this.rw = rw;
    return this;
  }

   /**
   * Get rw
   * @return rw
  **/
  public String getRw() {
    return rw;
  }

  public void setRw(String rw) {
    this.rw = rw;
  }

  public LocalNames sc(String sc) {
    this.sc = sc;
    return this;
  }

   /**
   * Get sc
   * @return sc
  **/
  public String getSc() {
    return sc;
  }

  public void setSc(String sc) {
    this.sc = sc;
  }

  public LocalNames sd(String sd) {
    this.sd = sd;
    return this;
  }

   /**
   * Get sd
   * @return sd
  **/
  public String getSd() {
    return sd;
  }

  public void setSd(String sd) {
    this.sd = sd;
  }

  public LocalNames se(String se) {
    this.se = se;
    return this;
  }

   /**
   * Get se
   * @return se
  **/
  public String getSe() {
    return se;
  }

  public void setSe(String se) {
    this.se = se;
  }

  public LocalNames si(String si) {
    this.si = si;
    return this;
  }

   /**
   * Get si
   * @return si
  **/
  public String getSi() {
    return si;
  }

  public void setSi(String si) {
    this.si = si;
  }

  public LocalNames sk(String sk) {
    this.sk = sk;
    return this;
  }

   /**
   * Get sk
   * @return sk
  **/
  public String getSk() {
    return sk;
  }

  public void setSk(String sk) {
    this.sk = sk;
  }

  public LocalNames sl(String sl) {
    this.sl = sl;
    return this;
  }

   /**
   * Get sl
   * @return sl
  **/
  public String getSl() {
    return sl;
  }

  public void setSl(String sl) {
    this.sl = sl;
  }

  public LocalNames sm(String sm) {
    this.sm = sm;
    return this;
  }

   /**
   * Get sm
   * @return sm
  **/
  public String getSm() {
    return sm;
  }

  public void setSm(String sm) {
    this.sm = sm;
  }

  public LocalNames so(String so) {
    this.so = so;
    return this;
  }

   /**
   * Get so
   * @return so
  **/
  public String getSo() {
    return so;
  }

  public void setSo(String so) {
    this.so = so;
  }

  public LocalNames sq(String sq) {
    this.sq = sq;
    return this;
  }

   /**
   * Get sq
   * @return sq
  **/
  public String getSq() {
    return sq;
  }

  public void setSq(String sq) {
    this.sq = sq;
  }

  public LocalNames sr(String sr) {
    this.sr = sr;
    return this;
  }

   /**
   * Get sr
   * @return sr
  **/
  public String getSr() {
    return sr;
  }

  public void setSr(String sr) {
    this.sr = sr;
  }

  public LocalNames st(String st) {
    this.st = st;
    return this;
  }

   /**
   * Get st
   * @return st
  **/
  public String getSt() {
    return st;
  }

  public void setSt(String st) {
    this.st = st;
  }

  public LocalNames sv(String sv) {
    this.sv = sv;
    return this;
  }

   /**
   * Get sv
   * @return sv
  **/
  public String getSv() {
    return sv;
  }

  public void setSv(String sv) {
    this.sv = sv;
  }

  public LocalNames sw(String sw) {
    this.sw = sw;
    return this;
  }

   /**
   * Get sw
   * @return sw
  **/
  public String getSw() {
    return sw;
  }

  public void setSw(String sw) {
    this.sw = sw;
  }

  public LocalNames ta(String ta) {
    this.ta = ta;
    return this;
  }

   /**
   * Get ta
   * @return ta
  **/
  public String getTa() {
    return ta;
  }

  public void setTa(String ta) {
    this.ta = ta;
  }

  public LocalNames te(String te) {
    this.te = te;
    return this;
  }

   /**
   * Get te
   * @return te
  **/
  public String getTe() {
    return te;
  }

  public void setTe(String te) {
    this.te = te;
  }

  public LocalNames tg(String tg) {
    this.tg = tg;
    return this;
  }

   /**
   * Get tg
   * @return tg
  **/
  public String getTg() {
    return tg;
  }

  public void setTg(String tg) {
    this.tg = tg;
  }

  public LocalNames th(String th) {
    this.th = th;
    return this;
  }

   /**
   * Get th
   * @return th
  **/
  public String getTh() {
    return th;
  }

  public void setTh(String th) {
    this.th = th;
  }

  public LocalNames tl(String tl) {
    this.tl = tl;
    return this;
  }

   /**
   * Get tl
   * @return tl
  **/
  public String getTl() {
    return tl;
  }

  public void setTl(String tl) {
    this.tl = tl;
  }

  public LocalNames to(String to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }

  public LocalNames tr(String tr) {
    this.tr = tr;
    return this;
  }

   /**
   * Get tr
   * @return tr
  **/
  public String getTr() {
    return tr;
  }

  public void setTr(String tr) {
    this.tr = tr;
  }

  public LocalNames tw(String tw) {
    this.tw = tw;
    return this;
  }

   /**
   * Get tw
   * @return tw
  **/
  public String getTw() {
    return tw;
  }

  public void setTw(String tw) {
    this.tw = tw;
  }

  public LocalNames ug(String ug) {
    this.ug = ug;
    return this;
  }

   /**
   * Get ug
   * @return ug
  **/
  public String getUg() {
    return ug;
  }

  public void setUg(String ug) {
    this.ug = ug;
  }

  public LocalNames uk(String uk) {
    this.uk = uk;
    return this;
  }

   /**
   * Get uk
   * @return uk
  **/
  public String getUk() {
    return uk;
  }

  public void setUk(String uk) {
    this.uk = uk;
  }

  public LocalNames ur(String ur) {
    this.ur = ur;
    return this;
  }

   /**
   * Get ur
   * @return ur
  **/
  public String getUr() {
    return ur;
  }

  public void setUr(String ur) {
    this.ur = ur;
  }

  public LocalNames uz(String uz) {
    this.uz = uz;
    return this;
  }

   /**
   * Get uz
   * @return uz
  **/
  public String getUz() {
    return uz;
  }

  public void setUz(String uz) {
    this.uz = uz;
  }

  public LocalNames vi(String vi) {
    this.vi = vi;
    return this;
  }

   /**
   * Get vi
   * @return vi
  **/
  public String getVi() {
    return vi;
  }

  public void setVi(String vi) {
    this.vi = vi;
  }

  public LocalNames wo(String wo) {
    this.wo = wo;
    return this;
  }

   /**
   * Get wo
   * @return wo
  **/
  public String getWo() {
    return wo;
  }

  public void setWo(String wo) {
    this.wo = wo;
  }

  public LocalNames xh(String xh) {
    this.xh = xh;
    return this;
  }

   /**
   * Get xh
   * @return xh
  **/
  public String getXh() {
    return xh;
  }

  public void setXh(String xh) {
    this.xh = xh;
  }

  public LocalNames yi(String yi) {
    this.yi = yi;
    return this;
  }

   /**
   * Get yi
   * @return yi
  **/
  public String getYi() {
    return yi;
  }

  public void setYi(String yi) {
    this.yi = yi;
  }

  public LocalNames yo(String yo) {
    this.yo = yo;
    return this;
  }

   /**
   * Get yo
   * @return yo
  **/
  public String getYo() {
    return yo;
  }

  public void setYo(String yo) {
    this.yo = yo;
  }

  public LocalNames zh(String zh) {
    this.zh = zh;
    return this;
  }

   /**
   * Get zh
   * @return zh
  **/
  public String getZh() {
    return zh;
  }

  public void setZh(String zh) {
    this.zh = zh;
  }

  public LocalNames zu(String zu) {
    this.zu = zu;
    return this;
  }

   /**
   * Get zu
   * @return zu
  **/
  public String getZu() {
    return zu;
  }

  public void setZu(String zu) {
    this.zu = zu;
  }

  public LocalNames ascii(String ascii) {
    this.ascii = ascii;
    return this;
  }

   /**
   * Get ascii
   * @return ascii
  **/
  public String getAscii() {
    return ascii;
  }

  public void setAscii(String ascii) {
    this.ascii = ascii;
  }

  public LocalNames featureName(String featureName) {
    this.featureName = featureName;
    return this;
  }

   /**
   * Get featureName
   * @return featureName
  **/
  public String getFeatureName() {
    return featureName;
  }

  public void setFeatureName(String featureName) {
    this.featureName = featureName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocalNames localNames = (LocalNames) o;
    return Objects.equals(this.ab, localNames.ab) &&
        Objects.equals(this.af, localNames.af) &&
        Objects.equals(this.an, localNames.an) &&
        Objects.equals(this.ar, localNames.ar) &&
        Objects.equals(this.av, localNames.av) &&
        Objects.equals(this.ay, localNames.ay) &&
        Objects.equals(this.az, localNames.az) &&
        Objects.equals(this.be, localNames.be) &&
        Objects.equals(this.bg, localNames.bg) &&
        Objects.equals(this.bh, localNames.bh) &&
        Objects.equals(this.bi, localNames.bi) &&
        Objects.equals(this.bm, localNames.bm) &&
        Objects.equals(this.bn, localNames.bn) &&
        Objects.equals(this.bo, localNames.bo) &&
        Objects.equals(this.br, localNames.br) &&
        Objects.equals(this.bs, localNames.bs) &&
        Objects.equals(this.ca, localNames.ca) &&
        Objects.equals(this.ce, localNames.ce) &&
        Objects.equals(this.co, localNames.co) &&
        Objects.equals(this.cs, localNames.cs) &&
        Objects.equals(this.cu, localNames.cu) &&
        Objects.equals(this.cy, localNames.cy) &&
        Objects.equals(this.da, localNames.da) &&
        Objects.equals(this.de, localNames.de) &&
        Objects.equals(this.ee, localNames.ee) &&
        Objects.equals(this.el, localNames.el) &&
        Objects.equals(this.en, localNames.en) &&
        Objects.equals(this.eo, localNames.eo) &&
        Objects.equals(this.es, localNames.es) &&
        Objects.equals(this.et, localNames.et) &&
        Objects.equals(this.eu, localNames.eu) &&
        Objects.equals(this.fa, localNames.fa) &&
        Objects.equals(this.ff, localNames.ff) &&
        Objects.equals(this.fi, localNames.fi) &&
        Objects.equals(this.fj, localNames.fj) &&
        Objects.equals(this.fo, localNames.fo) &&
        Objects.equals(this.fr, localNames.fr) &&
        Objects.equals(this.fy, localNames.fy) &&
        Objects.equals(this.ga, localNames.ga) &&
        Objects.equals(this.gd, localNames.gd) &&
        Objects.equals(this.gl, localNames.gl) &&
        Objects.equals(this.gn, localNames.gn) &&
        Objects.equals(this.gu, localNames.gu) &&
        Objects.equals(this.ha, localNames.ha) &&
        Objects.equals(this.he, localNames.he) &&
        Objects.equals(this.hi, localNames.hi) &&
        Objects.equals(this.hr, localNames.hr) &&
        Objects.equals(this.ht, localNames.ht) &&
        Objects.equals(this.hu, localNames.hu) &&
        Objects.equals(this.ia, localNames.ia) &&
        Objects.equals(this.id, localNames.id) &&
        Objects.equals(this.ig, localNames.ig) &&
        Objects.equals(this.is, localNames.is) &&
        Objects.equals(this.it, localNames.it) &&
        Objects.equals(this.ja, localNames.ja) &&
        Objects.equals(this.jv, localNames.jv) &&
        Objects.equals(this.ka, localNames.ka) &&
        Objects.equals(this.kk, localNames.kk) &&
        Objects.equals(this.km, localNames.km) &&
        Objects.equals(this.kn, localNames.kn) &&
        Objects.equals(this.ko, localNames.ko) &&
        Objects.equals(this.ku, localNames.ku) &&
        Objects.equals(this.kw, localNames.kw) &&
        Objects.equals(this.ky, localNames.ky) &&
        Objects.equals(this.lb, localNames.lb) &&
        Objects.equals(this.li, localNames.li) &&
        Objects.equals(this.ln, localNames.ln) &&
        Objects.equals(this.lo, localNames.lo) &&
        Objects.equals(this.lt, localNames.lt) &&
        Objects.equals(this.lv, localNames.lv) &&
        Objects.equals(this.mg, localNames.mg) &&
        Objects.equals(this.mi, localNames.mi) &&
        Objects.equals(this.mk, localNames.mk) &&
        Objects.equals(this.ml, localNames.ml) &&
        Objects.equals(this.mn, localNames.mn) &&
        Objects.equals(this.mr, localNames.mr) &&
        Objects.equals(this.ms, localNames.ms) &&
        Objects.equals(this.mt, localNames.mt) &&
        Objects.equals(this.my, localNames.my) &&
        Objects.equals(this.na, localNames.na) &&
        Objects.equals(this.nb, localNames.nb) &&
        Objects.equals(this.ne, localNames.ne) &&
        Objects.equals(this.nl, localNames.nl) &&
        Objects.equals(this.nn, localNames.nn) &&
        Objects.equals(this.no, localNames.no) &&
        Objects.equals(this.nv, localNames.nv) &&
        Objects.equals(this.ny, localNames.ny) &&
        Objects.equals(this.oc, localNames.oc) &&
        Objects.equals(this.or, localNames.or) &&
        Objects.equals(this.os, localNames.os) &&
        Objects.equals(this.pa, localNames.pa) &&
        Objects.equals(this.pl, localNames.pl) &&
        Objects.equals(this.ps, localNames.ps) &&
        Objects.equals(this.pt, localNames.pt) &&
        Objects.equals(this.qu, localNames.qu) &&
        Objects.equals(this.ro, localNames.ro) &&
        Objects.equals(this.ru, localNames.ru) &&
        Objects.equals(this.rw, localNames.rw) &&
        Objects.equals(this.sc, localNames.sc) &&
        Objects.equals(this.sd, localNames.sd) &&
        Objects.equals(this.se, localNames.se) &&
        Objects.equals(this.si, localNames.si) &&
        Objects.equals(this.sk, localNames.sk) &&
        Objects.equals(this.sl, localNames.sl) &&
        Objects.equals(this.sm, localNames.sm) &&
        Objects.equals(this.so, localNames.so) &&
        Objects.equals(this.sq, localNames.sq) &&
        Objects.equals(this.sr, localNames.sr) &&
        Objects.equals(this.st, localNames.st) &&
        Objects.equals(this.sv, localNames.sv) &&
        Objects.equals(this.sw, localNames.sw) &&
        Objects.equals(this.ta, localNames.ta) &&
        Objects.equals(this.te, localNames.te) &&
        Objects.equals(this.tg, localNames.tg) &&
        Objects.equals(this.th, localNames.th) &&
        Objects.equals(this.tl, localNames.tl) &&
        Objects.equals(this.to, localNames.to) &&
        Objects.equals(this.tr, localNames.tr) &&
        Objects.equals(this.tw, localNames.tw) &&
        Objects.equals(this.ug, localNames.ug) &&
        Objects.equals(this.uk, localNames.uk) &&
        Objects.equals(this.ur, localNames.ur) &&
        Objects.equals(this.uz, localNames.uz) &&
        Objects.equals(this.vi, localNames.vi) &&
        Objects.equals(this.wo, localNames.wo) &&
        Objects.equals(this.xh, localNames.xh) &&
        Objects.equals(this.yi, localNames.yi) &&
        Objects.equals(this.yo, localNames.yo) &&
        Objects.equals(this.zh, localNames.zh) &&
        Objects.equals(this.zu, localNames.zu) &&
        Objects.equals(this.ascii, localNames.ascii) &&
        Objects.equals(this.featureName, localNames.featureName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ab, af, an, ar, av, ay, az, be, bg, bh, bi, bm, bn, bo, br, bs, ca, ce, co, cs, cu, cy, da, de, ee, el, en, eo, es, et, eu, fa, ff, fi, fj, fo, fr, fy, ga, gd, gl, gn, gu, ha, he, hi, hr, ht, hu, ia, id, ig, is, it, ja, jv, ka, kk, km, kn, ko, ku, kw, ky, lb, li, ln, lo, lt, lv, mg, mi, mk, ml, mn, mr, ms, mt, my, na, nb, ne, nl, nn, no, nv, ny, oc, or, os, pa, pl, ps, pt, qu, ro, ru, rw, sc, sd, se, si, sk, sl, sm, so, sq, sr, st, sv, sw, ta, te, tg, th, tl, to, tr, tw, ug, uk, ur, uz, vi, wo, xh, yi, yo, zh, zu, ascii, featureName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocalNames {\n");
    
    sb.append("    ab: ").append(toIndentedString(ab)).append("\n");
    sb.append("    af: ").append(toIndentedString(af)).append("\n");
    sb.append("    an: ").append(toIndentedString(an)).append("\n");
    sb.append("    ar: ").append(toIndentedString(ar)).append("\n");
    sb.append("    av: ").append(toIndentedString(av)).append("\n");
    sb.append("    ay: ").append(toIndentedString(ay)).append("\n");
    sb.append("    az: ").append(toIndentedString(az)).append("\n");
    sb.append("    be: ").append(toIndentedString(be)).append("\n");
    sb.append("    bg: ").append(toIndentedString(bg)).append("\n");
    sb.append("    bh: ").append(toIndentedString(bh)).append("\n");
    sb.append("    bi: ").append(toIndentedString(bi)).append("\n");
    sb.append("    bm: ").append(toIndentedString(bm)).append("\n");
    sb.append("    bn: ").append(toIndentedString(bn)).append("\n");
    sb.append("    bo: ").append(toIndentedString(bo)).append("\n");
    sb.append("    br: ").append(toIndentedString(br)).append("\n");
    sb.append("    bs: ").append(toIndentedString(bs)).append("\n");
    sb.append("    ca: ").append(toIndentedString(ca)).append("\n");
    sb.append("    ce: ").append(toIndentedString(ce)).append("\n");
    sb.append("    co: ").append(toIndentedString(co)).append("\n");
    sb.append("    cs: ").append(toIndentedString(cs)).append("\n");
    sb.append("    cu: ").append(toIndentedString(cu)).append("\n");
    sb.append("    cy: ").append(toIndentedString(cy)).append("\n");
    sb.append("    da: ").append(toIndentedString(da)).append("\n");
    sb.append("    de: ").append(toIndentedString(de)).append("\n");
    sb.append("    ee: ").append(toIndentedString(ee)).append("\n");
    sb.append("    el: ").append(toIndentedString(el)).append("\n");
    sb.append("    en: ").append(toIndentedString(en)).append("\n");
    sb.append("    eo: ").append(toIndentedString(eo)).append("\n");
    sb.append("    es: ").append(toIndentedString(es)).append("\n");
    sb.append("    et: ").append(toIndentedString(et)).append("\n");
    sb.append("    eu: ").append(toIndentedString(eu)).append("\n");
    sb.append("    fa: ").append(toIndentedString(fa)).append("\n");
    sb.append("    ff: ").append(toIndentedString(ff)).append("\n");
    sb.append("    fi: ").append(toIndentedString(fi)).append("\n");
    sb.append("    fj: ").append(toIndentedString(fj)).append("\n");
    sb.append("    fo: ").append(toIndentedString(fo)).append("\n");
    sb.append("    fr: ").append(toIndentedString(fr)).append("\n");
    sb.append("    fy: ").append(toIndentedString(fy)).append("\n");
    sb.append("    ga: ").append(toIndentedString(ga)).append("\n");
    sb.append("    gd: ").append(toIndentedString(gd)).append("\n");
    sb.append("    gl: ").append(toIndentedString(gl)).append("\n");
    sb.append("    gn: ").append(toIndentedString(gn)).append("\n");
    sb.append("    gu: ").append(toIndentedString(gu)).append("\n");
    sb.append("    ha: ").append(toIndentedString(ha)).append("\n");
    sb.append("    he: ").append(toIndentedString(he)).append("\n");
    sb.append("    hi: ").append(toIndentedString(hi)).append("\n");
    sb.append("    hr: ").append(toIndentedString(hr)).append("\n");
    sb.append("    ht: ").append(toIndentedString(ht)).append("\n");
    sb.append("    hu: ").append(toIndentedString(hu)).append("\n");
    sb.append("    ia: ").append(toIndentedString(ia)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ig: ").append(toIndentedString(ig)).append("\n");
    sb.append("    is: ").append(toIndentedString(is)).append("\n");
    sb.append("    it: ").append(toIndentedString(it)).append("\n");
    sb.append("    ja: ").append(toIndentedString(ja)).append("\n");
    sb.append("    jv: ").append(toIndentedString(jv)).append("\n");
    sb.append("    ka: ").append(toIndentedString(ka)).append("\n");
    sb.append("    kk: ").append(toIndentedString(kk)).append("\n");
    sb.append("    km: ").append(toIndentedString(km)).append("\n");
    sb.append("    kn: ").append(toIndentedString(kn)).append("\n");
    sb.append("    ko: ").append(toIndentedString(ko)).append("\n");
    sb.append("    ku: ").append(toIndentedString(ku)).append("\n");
    sb.append("    kw: ").append(toIndentedString(kw)).append("\n");
    sb.append("    ky: ").append(toIndentedString(ky)).append("\n");
    sb.append("    lb: ").append(toIndentedString(lb)).append("\n");
    sb.append("    li: ").append(toIndentedString(li)).append("\n");
    sb.append("    ln: ").append(toIndentedString(ln)).append("\n");
    sb.append("    lo: ").append(toIndentedString(lo)).append("\n");
    sb.append("    lt: ").append(toIndentedString(lt)).append("\n");
    sb.append("    lv: ").append(toIndentedString(lv)).append("\n");
    sb.append("    mg: ").append(toIndentedString(mg)).append("\n");
    sb.append("    mi: ").append(toIndentedString(mi)).append("\n");
    sb.append("    mk: ").append(toIndentedString(mk)).append("\n");
    sb.append("    ml: ").append(toIndentedString(ml)).append("\n");
    sb.append("    mn: ").append(toIndentedString(mn)).append("\n");
    sb.append("    mr: ").append(toIndentedString(mr)).append("\n");
    sb.append("    ms: ").append(toIndentedString(ms)).append("\n");
    sb.append("    mt: ").append(toIndentedString(mt)).append("\n");
    sb.append("    my: ").append(toIndentedString(my)).append("\n");
    sb.append("    na: ").append(toIndentedString(na)).append("\n");
    sb.append("    nb: ").append(toIndentedString(nb)).append("\n");
    sb.append("    ne: ").append(toIndentedString(ne)).append("\n");
    sb.append("    nl: ").append(toIndentedString(nl)).append("\n");
    sb.append("    nn: ").append(toIndentedString(nn)).append("\n");
    sb.append("    no: ").append(toIndentedString(no)).append("\n");
    sb.append("    nv: ").append(toIndentedString(nv)).append("\n");
    sb.append("    ny: ").append(toIndentedString(ny)).append("\n");
    sb.append("    oc: ").append(toIndentedString(oc)).append("\n");
    sb.append("    or: ").append(toIndentedString(or)).append("\n");
    sb.append("    os: ").append(toIndentedString(os)).append("\n");
    sb.append("    pa: ").append(toIndentedString(pa)).append("\n");
    sb.append("    pl: ").append(toIndentedString(pl)).append("\n");
    sb.append("    ps: ").append(toIndentedString(ps)).append("\n");
    sb.append("    pt: ").append(toIndentedString(pt)).append("\n");
    sb.append("    qu: ").append(toIndentedString(qu)).append("\n");
    sb.append("    ro: ").append(toIndentedString(ro)).append("\n");
    sb.append("    ru: ").append(toIndentedString(ru)).append("\n");
    sb.append("    rw: ").append(toIndentedString(rw)).append("\n");
    sb.append("    sc: ").append(toIndentedString(sc)).append("\n");
    sb.append("    sd: ").append(toIndentedString(sd)).append("\n");
    sb.append("    se: ").append(toIndentedString(se)).append("\n");
    sb.append("    si: ").append(toIndentedString(si)).append("\n");
    sb.append("    sk: ").append(toIndentedString(sk)).append("\n");
    sb.append("    sl: ").append(toIndentedString(sl)).append("\n");
    sb.append("    sm: ").append(toIndentedString(sm)).append("\n");
    sb.append("    so: ").append(toIndentedString(so)).append("\n");
    sb.append("    sq: ").append(toIndentedString(sq)).append("\n");
    sb.append("    sr: ").append(toIndentedString(sr)).append("\n");
    sb.append("    st: ").append(toIndentedString(st)).append("\n");
    sb.append("    sv: ").append(toIndentedString(sv)).append("\n");
    sb.append("    sw: ").append(toIndentedString(sw)).append("\n");
    sb.append("    ta: ").append(toIndentedString(ta)).append("\n");
    sb.append("    te: ").append(toIndentedString(te)).append("\n");
    sb.append("    tg: ").append(toIndentedString(tg)).append("\n");
    sb.append("    th: ").append(toIndentedString(th)).append("\n");
    sb.append("    tl: ").append(toIndentedString(tl)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    tr: ").append(toIndentedString(tr)).append("\n");
    sb.append("    tw: ").append(toIndentedString(tw)).append("\n");
    sb.append("    ug: ").append(toIndentedString(ug)).append("\n");
    sb.append("    uk: ").append(toIndentedString(uk)).append("\n");
    sb.append("    ur: ").append(toIndentedString(ur)).append("\n");
    sb.append("    uz: ").append(toIndentedString(uz)).append("\n");
    sb.append("    vi: ").append(toIndentedString(vi)).append("\n");
    sb.append("    wo: ").append(toIndentedString(wo)).append("\n");
    sb.append("    xh: ").append(toIndentedString(xh)).append("\n");
    sb.append("    yi: ").append(toIndentedString(yi)).append("\n");
    sb.append("    yo: ").append(toIndentedString(yo)).append("\n");
    sb.append("    zh: ").append(toIndentedString(zh)).append("\n");
    sb.append("    zu: ").append(toIndentedString(zu)).append("\n");
    sb.append("    ascii: ").append(toIndentedString(ascii)).append("\n");
    sb.append("    featureName: ").append(toIndentedString(featureName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
