/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import org.openweathermap.api.data2_5.client.AirPollutionComponents;
import org.openweathermap.api.data2_5.client.AirPollutionMain;
/**
 * AirPollutionRecord
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class AirPollutionRecord {
  @JsonProperty("dt")
  private Long dt = null;

  @JsonProperty("main")
  private AirPollutionMain main = null;

  @JsonProperty("components")
  private AirPollutionComponents components = null;

  public AirPollutionRecord dt(Long dt) {
    this.dt = dt;
    return this;
  }

   /**
   * Get dt
   * @return dt
  **/
  public Long getDt() {
    return dt;
  }

  public void setDt(Long dt) {
    this.dt = dt;
  }

  public AirPollutionRecord main(AirPollutionMain main) {
    this.main = main;
    return this;
  }

   /**
   * Get main
   * @return main
  **/
  public AirPollutionMain getMain() {
    return main;
  }

  public void setMain(AirPollutionMain main) {
    this.main = main;
  }

  public AirPollutionRecord components(AirPollutionComponents components) {
    this.components = components;
    return this;
  }

   /**
   * Get components
   * @return components
  **/
  public AirPollutionComponents getComponents() {
    return components;
  }

  public void setComponents(AirPollutionComponents components) {
    this.components = components;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AirPollutionRecord airPollutionRecord = (AirPollutionRecord) o;
    return Objects.equals(this.dt, airPollutionRecord.dt) &&
        Objects.equals(this.main, airPollutionRecord.main) &&
        Objects.equals(this.components, airPollutionRecord.components);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dt, main, components);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AirPollutionRecord {\n");
    
    sb.append("    dt: ").append(toIndentedString(dt)).append("\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
