/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AirPollutionMain
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class AirPollutionMain {
  @JsonProperty("aqi")
  private Integer aqi = null;

  public AirPollutionMain aqi(Integer aqi) {
    this.aqi = aqi;
    return this;
  }

   /**
   * Get aqi
   * @return aqi
  **/
  public Integer getAqi() {
    return aqi;
  }

  public void setAqi(Integer aqi) {
    this.aqi = aqi;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AirPollutionMain airPollutionMain = (AirPollutionMain) o;
    return Objects.equals(this.aqi, airPollutionMain.aqi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aqi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AirPollutionMain {\n");
    
    sb.append("    aqi: ").append(toIndentedString(aqi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
