/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.openweathermap.api.data2_5.client.AirPollutionRecord;
import org.openweathermap.api.data2_5.client.Coord;
/**
 * AirPollution
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class AirPollution {
  @JsonProperty("coord")
  private Coord coord = null;

  @JsonProperty("list")
  private List<AirPollutionRecord> list = null;

  public AirPollution coord(Coord coord) {
    this.coord = coord;
    return this;
  }

   /**
   * Get coord
   * @return coord
  **/
  public Coord getCoord() {
    return coord;
  }

  public void setCoord(Coord coord) {
    this.coord = coord;
  }

  public AirPollution list(List<AirPollutionRecord> list) {
    this.list = list;
    return this;
  }

  public AirPollution addListItem(AirPollutionRecord listItem) {
    if (this.list == null) {
      this.list = new ArrayList<>();
    }
    this.list.add(listItem);
    return this;
  }

   /**
   * Get list
   * @return list
  **/
  public List<AirPollutionRecord> getList() {
    return list;
  }

  public void setList(List<AirPollutionRecord> list) {
    this.list = list;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AirPollution airPollution = (AirPollution) o;
    return Objects.equals(this.coord, airPollution.coord) &&
        Objects.equals(this.list, airPollution.list);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coord, list);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AirPollution {\n");
    
    sb.append("    coord: ").append(toIndentedString(coord)).append("\n");
    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
