/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AirPollutionComponents
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class AirPollutionComponents {
  @JsonProperty("co")
  private Float co = null;

  @JsonProperty("no")
  private Float no = null;

  @JsonProperty("no2")
  private Float no2 = null;

  @JsonProperty("o3")
  private Float o3 = null;

  @JsonProperty("so2")
  private Float so2 = null;

  @JsonProperty("pm2_5")
  private Float pm25 = null;

  @JsonProperty("pm10")
  private Float pm10 = null;

  @JsonProperty("nh3")
  private Float nh3 = null;

  public AirPollutionComponents co(Float co) {
    this.co = co;
    return this;
  }

   /**
   * Get co
   * @return co
  **/
  public Float getCo() {
    return co;
  }

  public void setCo(Float co) {
    this.co = co;
  }

  public AirPollutionComponents no(Float no) {
    this.no = no;
    return this;
  }

   /**
   * Get no
   * @return no
  **/
  public Float getNo() {
    return no;
  }

  public void setNo(Float no) {
    this.no = no;
  }

  public AirPollutionComponents no2(Float no2) {
    this.no2 = no2;
    return this;
  }

   /**
   * Get no2
   * @return no2
  **/
  public Float getNo2() {
    return no2;
  }

  public void setNo2(Float no2) {
    this.no2 = no2;
  }

  public AirPollutionComponents o3(Float o3) {
    this.o3 = o3;
    return this;
  }

   /**
   * Get o3
   * @return o3
  **/
  public Float getO3() {
    return o3;
  }

  public void setO3(Float o3) {
    this.o3 = o3;
  }

  public AirPollutionComponents so2(Float so2) {
    this.so2 = so2;
    return this;
  }

   /**
   * Get so2
   * @return so2
  **/
  public Float getSo2() {
    return so2;
  }

  public void setSo2(Float so2) {
    this.so2 = so2;
  }

  public AirPollutionComponents pm25(Float pm25) {
    this.pm25 = pm25;
    return this;
  }

   /**
   * Get pm25
   * @return pm25
  **/
  public Float getPm25() {
    return pm25;
  }

  public void setPm25(Float pm25) {
    this.pm25 = pm25;
  }

  public AirPollutionComponents pm10(Float pm10) {
    this.pm10 = pm10;
    return this;
  }

   /**
   * Get pm10
   * @return pm10
  **/
  public Float getPm10() {
    return pm10;
  }

  public void setPm10(Float pm10) {
    this.pm10 = pm10;
  }

  public AirPollutionComponents nh3(Float nh3) {
    this.nh3 = nh3;
    return this;
  }

   /**
   * Get nh3
   * @return nh3
  **/
  public Float getNh3() {
    return nh3;
  }

  public void setNh3(Float nh3) {
    this.nh3 = nh3;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AirPollutionComponents airPollutionComponents = (AirPollutionComponents) o;
    return Objects.equals(this.co, airPollutionComponents.co) &&
        Objects.equals(this.no, airPollutionComponents.no) &&
        Objects.equals(this.no2, airPollutionComponents.no2) &&
        Objects.equals(this.o3, airPollutionComponents.o3) &&
        Objects.equals(this.so2, airPollutionComponents.so2) &&
        Objects.equals(this.pm25, airPollutionComponents.pm25) &&
        Objects.equals(this.pm10, airPollutionComponents.pm10) &&
        Objects.equals(this.nh3, airPollutionComponents.nh3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(co, no, no2, o3, so2, pm25, pm10, nh3);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AirPollutionComponents {\n");
    
    sb.append("    co: ").append(toIndentedString(co)).append("\n");
    sb.append("    no: ").append(toIndentedString(no)).append("\n");
    sb.append("    no2: ").append(toIndentedString(no2)).append("\n");
    sb.append("    o3: ").append(toIndentedString(o3)).append("\n");
    sb.append("    so2: ").append(toIndentedString(so2)).append("\n");
    sb.append("    pm25: ").append(toIndentedString(pm25)).append("\n");
    sb.append("    pm10: ").append(toIndentedString(pm10)).append("\n");
    sb.append("    nh3: ").append(toIndentedString(nh3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
