/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import org.openweathermap.api.data2_5.client.Coord;
/**
 * City
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class City {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("coord")
  private Coord coord = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("population")
  private Integer population = null;

  @JsonProperty("timezone")
  private Integer timezone = null;

  @JsonProperty("sunrise")
  private Integer sunrise = null;

  @JsonProperty("sunset")
  private Integer sunset = null;

  public City id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public City name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public City coord(Coord coord) {
    this.coord = coord;
    return this;
  }

   /**
   * Get coord
   * @return coord
  **/
  public Coord getCoord() {
    return coord;
  }

  public void setCoord(Coord coord) {
    this.coord = coord;
  }

  public City country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public City population(Integer population) {
    this.population = population;
    return this;
  }

   /**
   * Get population
   * @return population
  **/
  public Integer getPopulation() {
    return population;
  }

  public void setPopulation(Integer population) {
    this.population = population;
  }

  public City timezone(Integer timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  public Integer getTimezone() {
    return timezone;
  }

  public void setTimezone(Integer timezone) {
    this.timezone = timezone;
  }

  public City sunrise(Integer sunrise) {
    this.sunrise = sunrise;
    return this;
  }

   /**
   * Get sunrise
   * @return sunrise
  **/
  public Integer getSunrise() {
    return sunrise;
  }

  public void setSunrise(Integer sunrise) {
    this.sunrise = sunrise;
  }

  public City sunset(Integer sunset) {
    this.sunset = sunset;
    return this;
  }

   /**
   * Get sunset
   * @return sunset
  **/
  public Integer getSunset() {
    return sunset;
  }

  public void setSunset(Integer sunset) {
    this.sunset = sunset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    City city = (City) o;
    return Objects.equals(this.id, city.id) &&
        Objects.equals(this.name, city.name) &&
        Objects.equals(this.coord, city.coord) &&
        Objects.equals(this.country, city.country) &&
        Objects.equals(this.population, city.population) &&
        Objects.equals(this.timezone, city.timezone) &&
        Objects.equals(this.sunrise, city.sunrise) &&
        Objects.equals(this.sunset, city.sunset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, coord, country, population, timezone, sunrise, sunset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class City {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    coord: ").append(toIndentedString(coord)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    population: ").append(toIndentedString(population)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    sunrise: ").append(toIndentedString(sunrise)).append("\n");
    sb.append("    sunset: ").append(toIndentedString(sunset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
