/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.openweathermap.api.data2_5.client.Clouds;
import org.openweathermap.api.data2_5.client.Coord;
import org.openweathermap.api.data2_5.client.Main;
import org.openweathermap.api.data2_5.client.Rain;
import org.openweathermap.api.data2_5.client.Sys;
import org.openweathermap.api.data2_5.client.Weather;
import org.openweathermap.api.data2_5.client.Wind;
/**
 * Current
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class Current {
  @JsonProperty("coord")
  private Coord coord = null;

  @JsonProperty("weather")
  private List<Weather> weather = null;

  @JsonProperty("base")
  private String base = null;

  @JsonProperty("main")
  private Main main = null;

  @JsonProperty("visibility")
  private Integer visibility = null;

  @JsonProperty("wind")
  private Wind wind = null;

  @JsonProperty("rain")
  private Rain rain = null;

  @JsonProperty("clouds")
  private Clouds clouds = null;

  @JsonProperty("dt")
  private Long dt = null;

  @JsonProperty("sys")
  private Sys sys = null;

  @JsonProperty("timezone")
  private Integer timezone = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("cod")
  private Integer cod = null;

  public Current coord(Coord coord) {
    this.coord = coord;
    return this;
  }

   /**
   * Get coord
   * @return coord
  **/
  public Coord getCoord() {
    return coord;
  }

  public void setCoord(Coord coord) {
    this.coord = coord;
  }

  public Current weather(List<Weather> weather) {
    this.weather = weather;
    return this;
  }

  public Current addWeatherItem(Weather weatherItem) {
    if (this.weather == null) {
      this.weather = new ArrayList<>();
    }
    this.weather.add(weatherItem);
    return this;
  }

   /**
   * Get weather
   * @return weather
  **/
  public List<Weather> getWeather() {
    return weather;
  }

  public void setWeather(List<Weather> weather) {
    this.weather = weather;
  }

  public Current base(String base) {
    this.base = base;
    return this;
  }

   /**
   * Get base
   * @return base
  **/
  public String getBase() {
    return base;
  }

  public void setBase(String base) {
    this.base = base;
  }

  public Current main(Main main) {
    this.main = main;
    return this;
  }

   /**
   * Get main
   * @return main
  **/
  public Main getMain() {
    return main;
  }

  public void setMain(Main main) {
    this.main = main;
  }

  public Current visibility(Integer visibility) {
    this.visibility = visibility;
    return this;
  }

   /**
   * Get visibility
   * @return visibility
  **/
  public Integer getVisibility() {
    return visibility;
  }

  public void setVisibility(Integer visibility) {
    this.visibility = visibility;
  }

  public Current wind(Wind wind) {
    this.wind = wind;
    return this;
  }

   /**
   * Get wind
   * @return wind
  **/
  public Wind getWind() {
    return wind;
  }

  public void setWind(Wind wind) {
    this.wind = wind;
  }

  public Current rain(Rain rain) {
    this.rain = rain;
    return this;
  }

   /**
   * Get rain
   * @return rain
  **/
  public Rain getRain() {
    return rain;
  }

  public void setRain(Rain rain) {
    this.rain = rain;
  }

  public Current clouds(Clouds clouds) {
    this.clouds = clouds;
    return this;
  }

   /**
   * Get clouds
   * @return clouds
  **/
  public Clouds getClouds() {
    return clouds;
  }

  public void setClouds(Clouds clouds) {
    this.clouds = clouds;
  }

  public Current dt(Long dt) {
    this.dt = dt;
    return this;
  }

   /**
   * Get dt
   * @return dt
  **/
  public Long getDt() {
    return dt;
  }

  public void setDt(Long dt) {
    this.dt = dt;
  }

  public Current sys(Sys sys) {
    this.sys = sys;
    return this;
  }

   /**
   * Get sys
   * @return sys
  **/
  public Sys getSys() {
    return sys;
  }

  public void setSys(Sys sys) {
    this.sys = sys;
  }

  public Current timezone(Integer timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  public Integer getTimezone() {
    return timezone;
  }

  public void setTimezone(Integer timezone) {
    this.timezone = timezone;
  }

  public Current id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Current name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Current cod(Integer cod) {
    this.cod = cod;
    return this;
  }

   /**
   * Get cod
   * @return cod
  **/
  public Integer getCod() {
    return cod;
  }

  public void setCod(Integer cod) {
    this.cod = cod;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Current current = (Current) o;
    return Objects.equals(this.coord, current.coord) &&
        Objects.equals(this.weather, current.weather) &&
        Objects.equals(this.base, current.base) &&
        Objects.equals(this.main, current.main) &&
        Objects.equals(this.visibility, current.visibility) &&
        Objects.equals(this.wind, current.wind) &&
        Objects.equals(this.rain, current.rain) &&
        Objects.equals(this.clouds, current.clouds) &&
        Objects.equals(this.dt, current.dt) &&
        Objects.equals(this.sys, current.sys) &&
        Objects.equals(this.timezone, current.timezone) &&
        Objects.equals(this.id, current.id) &&
        Objects.equals(this.name, current.name) &&
        Objects.equals(this.cod, current.cod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coord, weather, base, main, visibility, wind, rain, clouds, dt, sys, timezone, id, name, cod);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Current {\n");
    
    sb.append("    coord: ").append(toIndentedString(coord)).append("\n");
    sb.append("    weather: ").append(toIndentedString(weather)).append("\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    wind: ").append(toIndentedString(wind)).append("\n");
    sb.append("    rain: ").append(toIndentedString(rain)).append("\n");
    sb.append("    clouds: ").append(toIndentedString(clouds)).append("\n");
    sb.append("    dt: ").append(toIndentedString(dt)).append("\n");
    sb.append("    sys: ").append(toIndentedString(sys)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    cod: ").append(toIndentedString(cod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
