/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.openweathermap.api.data2_5.client.City;
import org.openweathermap.api.data2_5.client.WeatherRecord;
/**
 * Forecast
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class Forecast {
  @JsonProperty("cod")
  private String cod = null;

  @JsonProperty("message")
  private Integer message = null;

  @JsonProperty("cnt")
  private Integer cnt = null;

  @JsonProperty("list")
  private List<WeatherRecord> list = null;

  @JsonProperty("city")
  private City city = null;

  public Forecast cod(String cod) {
    this.cod = cod;
    return this;
  }

   /**
   * Get cod
   * @return cod
  **/
  public String getCod() {
    return cod;
  }

  public void setCod(String cod) {
    this.cod = cod;
  }

  public Forecast message(Integer message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  public Integer getMessage() {
    return message;
  }

  public void setMessage(Integer message) {
    this.message = message;
  }

  public Forecast cnt(Integer cnt) {
    this.cnt = cnt;
    return this;
  }

   /**
   * Get cnt
   * @return cnt
  **/
  public Integer getCnt() {
    return cnt;
  }

  public void setCnt(Integer cnt) {
    this.cnt = cnt;
  }

  public Forecast list(List<WeatherRecord> list) {
    this.list = list;
    return this;
  }

  public Forecast addListItem(WeatherRecord listItem) {
    if (this.list == null) {
      this.list = new ArrayList<>();
    }
    this.list.add(listItem);
    return this;
  }

   /**
   * Get list
   * @return list
  **/
  public List<WeatherRecord> getList() {
    return list;
  }

  public void setList(List<WeatherRecord> list) {
    this.list = list;
  }

  public Forecast city(City city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  public City getCity() {
    return city;
  }

  public void setCity(City city) {
    this.city = city;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Forecast forecast = (Forecast) o;
    return Objects.equals(this.cod, forecast.cod) &&
        Objects.equals(this.message, forecast.message) &&
        Objects.equals(this.cnt, forecast.cnt) &&
        Objects.equals(this.list, forecast.list) &&
        Objects.equals(this.city, forecast.city);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cod, message, cnt, list, city);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Forecast {\n");
    
    sb.append("    cod: ").append(toIndentedString(cod)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    cnt: ").append(toIndentedString(cnt)).append("\n");
    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
