/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Main
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class Main {
  @JsonProperty("temp")
  private Float temp = null;

  @JsonProperty("feels_like")
  private Float feelsLike = null;

  @JsonProperty("temp_min")
  private Float tempMin = null;

  @JsonProperty("temp_max")
  private Float tempMax = null;

  @JsonProperty("pressure")
  private Integer pressure = null;

  @JsonProperty("sea_level")
  private Integer seaLevel = null;

  @JsonProperty("grnd_level")
  private Integer grndLevel = null;

  @JsonProperty("humidity")
  private Integer humidity = null;

  @JsonProperty("temp_kf")
  private Float tempKf = null;

  public Main temp(Float temp) {
    this.temp = temp;
    return this;
  }

   /**
   * Get temp
   * @return temp
  **/
  public Float getTemp() {
    return temp;
  }

  public void setTemp(Float temp) {
    this.temp = temp;
  }

  public Main feelsLike(Float feelsLike) {
    this.feelsLike = feelsLike;
    return this;
  }

   /**
   * Get feelsLike
   * @return feelsLike
  **/
  public Float getFeelsLike() {
    return feelsLike;
  }

  public void setFeelsLike(Float feelsLike) {
    this.feelsLike = feelsLike;
  }

  public Main tempMin(Float tempMin) {
    this.tempMin = tempMin;
    return this;
  }

   /**
   * Get tempMin
   * @return tempMin
  **/
  public Float getTempMin() {
    return tempMin;
  }

  public void setTempMin(Float tempMin) {
    this.tempMin = tempMin;
  }

  public Main tempMax(Float tempMax) {
    this.tempMax = tempMax;
    return this;
  }

   /**
   * Get tempMax
   * @return tempMax
  **/
  public Float getTempMax() {
    return tempMax;
  }

  public void setTempMax(Float tempMax) {
    this.tempMax = tempMax;
  }

  public Main pressure(Integer pressure) {
    this.pressure = pressure;
    return this;
  }

   /**
   * Get pressure
   * @return pressure
  **/
  public Integer getPressure() {
    return pressure;
  }

  public void setPressure(Integer pressure) {
    this.pressure = pressure;
  }

  public Main seaLevel(Integer seaLevel) {
    this.seaLevel = seaLevel;
    return this;
  }

   /**
   * Get seaLevel
   * @return seaLevel
  **/
  public Integer getSeaLevel() {
    return seaLevel;
  }

  public void setSeaLevel(Integer seaLevel) {
    this.seaLevel = seaLevel;
  }

  public Main grndLevel(Integer grndLevel) {
    this.grndLevel = grndLevel;
    return this;
  }

   /**
   * Get grndLevel
   * @return grndLevel
  **/
  public Integer getGrndLevel() {
    return grndLevel;
  }

  public void setGrndLevel(Integer grndLevel) {
    this.grndLevel = grndLevel;
  }

  public Main humidity(Integer humidity) {
    this.humidity = humidity;
    return this;
  }

   /**
   * Get humidity
   * @return humidity
  **/
  public Integer getHumidity() {
    return humidity;
  }

  public void setHumidity(Integer humidity) {
    this.humidity = humidity;
  }

  public Main tempKf(Float tempKf) {
    this.tempKf = tempKf;
    return this;
  }

   /**
   * Get tempKf
   * @return tempKf
  **/
  public Float getTempKf() {
    return tempKf;
  }

  public void setTempKf(Float tempKf) {
    this.tempKf = tempKf;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Main main = (Main) o;
    return Objects.equals(this.temp, main.temp) &&
        Objects.equals(this.feelsLike, main.feelsLike) &&
        Objects.equals(this.tempMin, main.tempMin) &&
        Objects.equals(this.tempMax, main.tempMax) &&
        Objects.equals(this.pressure, main.pressure) &&
        Objects.equals(this.seaLevel, main.seaLevel) &&
        Objects.equals(this.grndLevel, main.grndLevel) &&
        Objects.equals(this.humidity, main.humidity) &&
        Objects.equals(this.tempKf, main.tempKf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(temp, feelsLike, tempMin, tempMax, pressure, seaLevel, grndLevel, humidity, tempKf);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Main {\n");
    
    sb.append("    temp: ").append(toIndentedString(temp)).append("\n");
    sb.append("    feelsLike: ").append(toIndentedString(feelsLike)).append("\n");
    sb.append("    tempMin: ").append(toIndentedString(tempMin)).append("\n");
    sb.append("    tempMax: ").append(toIndentedString(tempMax)).append("\n");
    sb.append("    pressure: ").append(toIndentedString(pressure)).append("\n");
    sb.append("    seaLevel: ").append(toIndentedString(seaLevel)).append("\n");
    sb.append("    grndLevel: ").append(toIndentedString(grndLevel)).append("\n");
    sb.append("    humidity: ").append(toIndentedString(humidity)).append("\n");
    sb.append("    tempKf: ").append(toIndentedString(tempKf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
