/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Rain
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class Rain {
  @JsonProperty("1h")
  private Float _1h = null;

  @JsonProperty("3h")
  private Float _3h = null;

  public Rain _1h(Float _1h) {
    this._1h = _1h;
    return this;
  }

   /**
   * Get _1h
   * @return _1h
  **/
  public Float get1h() {
    return _1h;
  }

  public void set1h(Float _1h) {
    this._1h = _1h;
  }

  public Rain _3h(Float _3h) {
    this._3h = _3h;
    return this;
  }

   /**
   * Get _3h
   * @return _3h
  **/
  public Float get3h() {
    return _3h;
  }

  public void set3h(Float _3h) {
    this._3h = _3h;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rain rain = (Rain) o;
    return Objects.equals(this._1h, rain._1h) &&
        Objects.equals(this._3h, rain._3h);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_1h, _3h);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rain {\n");
    
    sb.append("    _1h: ").append(toIndentedString(_1h)).append("\n");
    sb.append("    _3h: ").append(toIndentedString(_3h)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
