/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Sys
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class Sys {
  @JsonProperty("pod")
  private String pod = null;

  @JsonProperty("type")
  private Integer type = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("sunrise")
  private Integer sunrise = null;

  @JsonProperty("sunset")
  private Integer sunset = null;

  public Sys pod(String pod) {
    this.pod = pod;
    return this;
  }

   /**
   * Get pod
   * @return pod
  **/
  public String getPod() {
    return pod;
  }

  public void setPod(String pod) {
    this.pod = pod;
  }

  public Sys type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public Sys id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Sys country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public Sys sunrise(Integer sunrise) {
    this.sunrise = sunrise;
    return this;
  }

   /**
   * Get sunrise
   * @return sunrise
  **/
  public Integer getSunrise() {
    return sunrise;
  }

  public void setSunrise(Integer sunrise) {
    this.sunrise = sunrise;
  }

  public Sys sunset(Integer sunset) {
    this.sunset = sunset;
    return this;
  }

   /**
   * Get sunset
   * @return sunset
  **/
  public Integer getSunset() {
    return sunset;
  }

  public void setSunset(Integer sunset) {
    this.sunset = sunset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sys sys = (Sys) o;
    return Objects.equals(this.pod, sys.pod) &&
        Objects.equals(this.type, sys.type) &&
        Objects.equals(this.id, sys.id) &&
        Objects.equals(this.country, sys.country) &&
        Objects.equals(this.sunrise, sys.sunrise) &&
        Objects.equals(this.sunset, sys.sunset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pod, type, id, country, sunrise, sunset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sys {\n");
    
    sb.append("    pod: ").append(toIndentedString(pod)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    sunrise: ").append(toIndentedString(sunrise)).append("\n");
    sb.append("    sunset: ").append(toIndentedString(sunset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
