/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import org.openweathermap.api.data2_5.client.Clouds;
import org.openweathermap.api.data2_5.client.Main;
import org.openweathermap.api.data2_5.client.Rain;
import org.openweathermap.api.data2_5.client.Sys;
import org.openweathermap.api.data2_5.client.Weather;
import org.openweathermap.api.data2_5.client.Wind;
/**
 * WeatherRecord
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class WeatherRecord {
  @JsonProperty("dt")
  private Long dt = null;

  @JsonProperty("main")
  private Main main = null;

  @JsonProperty("weather")
  private List<Weather> weather = null;

  @JsonProperty("clouds")
  private Clouds clouds = null;

  @JsonProperty("wind")
  private Wind wind = null;

  @JsonProperty("visibility")
  private Integer visibility = null;

  @JsonProperty("pop")
  private Float pop = null;

  @JsonProperty("rain")
  private Rain rain = null;

  @JsonProperty("sys")
  private Sys sys = null;

  @JsonProperty("dt_txt")
  private String dtTxt = null;

  public WeatherRecord dt(Long dt) {
    this.dt = dt;
    return this;
  }

   /**
   * Get dt
   * @return dt
  **/
  public Long getDt() {
    return dt;
  }

  public void setDt(Long dt) {
    this.dt = dt;
  }

  public WeatherRecord main(Main main) {
    this.main = main;
    return this;
  }

   /**
   * Get main
   * @return main
  **/
  public Main getMain() {
    return main;
  }

  public void setMain(Main main) {
    this.main = main;
  }

  public WeatherRecord weather(List<Weather> weather) {
    this.weather = weather;
    return this;
  }

  public WeatherRecord addWeatherItem(Weather weatherItem) {
    if (this.weather == null) {
      this.weather = new ArrayList<>();
    }
    this.weather.add(weatherItem);
    return this;
  }

   /**
   * Get weather
   * @return weather
  **/
  public List<Weather> getWeather() {
    return weather;
  }

  public void setWeather(List<Weather> weather) {
    this.weather = weather;
  }

  public WeatherRecord clouds(Clouds clouds) {
    this.clouds = clouds;
    return this;
  }

   /**
   * Get clouds
   * @return clouds
  **/
  public Clouds getClouds() {
    return clouds;
  }

  public void setClouds(Clouds clouds) {
    this.clouds = clouds;
  }

  public WeatherRecord wind(Wind wind) {
    this.wind = wind;
    return this;
  }

   /**
   * Get wind
   * @return wind
  **/
  public Wind getWind() {
    return wind;
  }

  public void setWind(Wind wind) {
    this.wind = wind;
  }

  public WeatherRecord visibility(Integer visibility) {
    this.visibility = visibility;
    return this;
  }

   /**
   * Get visibility
   * @return visibility
  **/
  public Integer getVisibility() {
    return visibility;
  }

  public void setVisibility(Integer visibility) {
    this.visibility = visibility;
  }

  public WeatherRecord pop(Float pop) {
    this.pop = pop;
    return this;
  }

   /**
   * Get pop
   * @return pop
  **/
  public Float getPop() {
    return pop;
  }

  public void setPop(Float pop) {
    this.pop = pop;
  }

  public WeatherRecord rain(Rain rain) {
    this.rain = rain;
    return this;
  }

   /**
   * Get rain
   * @return rain
  **/
  public Rain getRain() {
    return rain;
  }

  public void setRain(Rain rain) {
    this.rain = rain;
  }

  public WeatherRecord sys(Sys sys) {
    this.sys = sys;
    return this;
  }

   /**
   * Get sys
   * @return sys
  **/
  public Sys getSys() {
    return sys;
  }

  public void setSys(Sys sys) {
    this.sys = sys;
  }

  public WeatherRecord dtTxt(String dtTxt) {
    this.dtTxt = dtTxt;
    return this;
  }

   /**
   * Get dtTxt
   * @return dtTxt
  **/
  public String getDtTxt() {
    return dtTxt;
  }

  public void setDtTxt(String dtTxt) {
    this.dtTxt = dtTxt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WeatherRecord weatherRecord = (WeatherRecord) o;
    return Objects.equals(this.dt, weatherRecord.dt) &&
        Objects.equals(this.main, weatherRecord.main) &&
        Objects.equals(this.weather, weatherRecord.weather) &&
        Objects.equals(this.clouds, weatherRecord.clouds) &&
        Objects.equals(this.wind, weatherRecord.wind) &&
        Objects.equals(this.visibility, weatherRecord.visibility) &&
        Objects.equals(this.pop, weatherRecord.pop) &&
        Objects.equals(this.rain, weatherRecord.rain) &&
        Objects.equals(this.sys, weatherRecord.sys) &&
        Objects.equals(this.dtTxt, weatherRecord.dtTxt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dt, main, weather, clouds, wind, visibility, pop, rain, sys, dtTxt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WeatherRecord {\n");
    
    sb.append("    dt: ").append(toIndentedString(dt)).append("\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("    weather: ").append(toIndentedString(weather)).append("\n");
    sb.append("    clouds: ").append(toIndentedString(clouds)).append("\n");
    sb.append("    wind: ").append(toIndentedString(wind)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    pop: ").append(toIndentedString(pop)).append("\n");
    sb.append("    rain: ").append(toIndentedString(rain)).append("\n");
    sb.append("    sys: ").append(toIndentedString(sys)).append("\n");
    sb.append("    dtTxt: ").append(toIndentedString(dtTxt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
