/*
 * Openweathermap weather API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.openweathermap.api.data2_5.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Wind
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-21T15:08:59.864393900+07:00[Asia/Bangkok]")
public class Wind {
  @JsonProperty("speed")
  private Float speed = null;

  @JsonProperty("deg")
  private Integer deg = null;

  @JsonProperty("gust")
  private Float gust = null;

  public Wind speed(Float speed) {
    this.speed = speed;
    return this;
  }

   /**
   * Get speed
   * @return speed
  **/
  public Float getSpeed() {
    return speed;
  }

  public void setSpeed(Float speed) {
    this.speed = speed;
  }

  public Wind deg(Integer deg) {
    this.deg = deg;
    return this;
  }

   /**
   * Get deg
   * @return deg
  **/
  public Integer getDeg() {
    return deg;
  }

  public void setDeg(Integer deg) {
    this.deg = deg;
  }

  public Wind gust(Float gust) {
    this.gust = gust;
    return this;
  }

   /**
   * Get gust
   * @return gust
  **/
  public Float getGust() {
    return gust;
  }

  public void setGust(Float gust) {
    this.gust = gust;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Wind wind = (Wind) o;
    return Objects.equals(this.speed, wind.speed) &&
        Objects.equals(this.deg, wind.deg) &&
        Objects.equals(this.gust, wind.gust);
  }

  @Override
  public int hashCode() {
    return Objects.hash(speed, deg, gust);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Wind {\n");
    
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    deg: ").append(toIndentedString(deg)).append("\n");
    sb.append("    gust: ").append(toIndentedString(gust)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
