Variables:
  openWeatherConnector:
    # Open Weather Data endpoint
    weatherDataUrl: 'https://api.openweathermap.org/data/2.5'
    
    # Open Weather Geo endpoint
    weatherGeoUrl: 'https://api.openweathermap.org/geo/1.0'
    
    # Your Open Weather connector Application Client ID
    appId: ''