Variables:
  openWeatherConnector:
    # Host to Open Weather connector
    host: 'api.openweathermap.org'

    # Open Weather Data URI
    weatherDataUri: 'https://{host}/data/2.5/'

    # Open Weather Geocoding URI
    weatherGeoUri: 'https://{host}/geo/1.0/'

    # Your Open Weather connector Application Client ID
    appId: ''