# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  openWeatherConnector:
    # Open Weather Data endpoint
    weatherDataUrl: ""
    # Open Weather Geo endpoint
    weatherGeoUrl: ""
    # Your Open Weather connector Application Client ID
    appId: ""
