# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/webservice-clients-2.json
WebServiceClients:
  httpapiopenweathermaporgdata25:
    Name: http://api.openweathermap.org/data/2.5
    WsdlUrl: http://api.openweathermap.org/data/2.5
    LegacyId: 18CFCB586A4A7FCB
