name: End-2-End Testing Build

on:
  schedule:
    - cron:  '0 1 * * 1'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@bugfix/MARP-2689-CI-workflow-failed-test-without-test-report
    secrets:
      mvnArgs: -Dopenweather.appId=${{ secrets.APP_ID }} -Dopenweather.weatherDataUrl=${{ secrets.WEATHER_DATA_URL }} -Dopenweather.weatherGeoUrl=${{ secrets.WEATHER_GEO_URL }} "-DtestEnvironment=${{ secrets.END_2_END_TESTING_ENV }}"